### PR TITLE
Migrate to kotest 4.0.3

### PR DESCRIPTION
**Pull request by Harrypulvirenti**
Migrate to KoTest 4.0.3

### CODE REVIEW

**Comment by dcampogiani** [comment]
Any update on this?

**Comment by dcampogiani** [comment]
any ETA?

**Comment by dcampogiani** [comment]
Hi Enrico,

I hope you're doing well. I'm really excited about the new feature that was mentioned in this issue. I understand that development timelines can be challenging to pin down, but I was hoping you might have a rough estimate for when we might expect it to be available.

I appreciate all the hard work you and the team are putting into this project. Any information you can provide would be greatly appreciated as it will help us plan our upcoming activities.

Thank you so much!

Best regards,
Daniele

**Comment by Harrypulvirenti** [comment]
Hi @dcampogiani as you can see this side project was stopped and is not in active development state as you can clearly see from my last commit that is basically of 4 years ago.
Going to close this since there is no expected ETA for a dead project

**Pull request closed without merging**
